### PR TITLE
Stack

### PR DESCRIPTION
**Pull request by Kamui-Solo**
Picking stack color from favicon, ithinc removed this feature, but I think it's very interestштп feature.

### CODE REVIEW

**Comment by yfdyh000** [comment]
Although I usually don't use the tabstack feature (`extensions.tabutils.autoStack`=false), 
But I feel don't like this feature, it is sometimes uses a not beautiful colors (e.g. black).

If you found other supporters, or add a pref and not enabled by default, maybe I'll consider adding it.
Thank you for your patches, I look forward to more.

**Comment by Kamui-Solo** [comment]
I add pref for this, it seems to work. And it's not enabled by defaul and besides it's still possible to recolor stack from context menu of tab.

**Comment by yfdyh000** [comment]
Why the `TU_getPref('extensions.tabutils.colorStackFromFavicon', 0)` is 0 instead of `false`?
And, you should git squashing these commits into one commit, for a clean commits history.

**Comment by Kamui-Solo** [comment]
I don't know how to do it. I'm really not experienced in github and programming. What if I will recreate fork and try to commit from git shell, because before i do it from web interface.

**Comment by yfdyh000** [comment]
OK, I'll finish it on my local. As well, maybe I don't need a separate release for this feature?

**Comment by Kamui-Solo** [comment]
I don't know, but i want to use your fork in future, besides this feature optional and I would like to see it in your fork.
Oh and `TU_getPref('extensions.tabutils.colorStackFromFavicon', 0)` must be `true`

**Comment by yfdyh000** [comment]
It will appear in the next release in future, but I think I should not release a release for small change, it is an email notification to all watchers.

I hope I have done relatively correct operation, squashed and forced push on d999da75226c63f088417eb214d96980b30c18d0.

**Comment by Kamui-Solo** [comment]
Ok, I agree with your opinion about release for small change.
I don't understand, but looks like it's important `true` or `false` in `TU_getPref('extensions.tabutils.colorStackFromFavicon',)`

**Comment by yfdyh000** [comment]
Yes, it on d999da75226c63f088417eb214d96980b30c18d0 for to `false`.

**Comment by ShunYea** [comment]
安装了新版本，第一个（最左侧）的标签页会有一部分延伸到屏幕外了，大概有一个ICO的位置不显示了，就是太靠左了，必须到设置里面将：外观-标签栏“左侧额外空间”勾选上才能正常，以前不需要勾选也是可以用的。从更新了3.30版开始发现这个问题。

**Comment by yfdyh000** [comment]
@ShunYea 已知问题，修复的方案有误，暂时没时间重新研究，#21。

**Pull request merged**
