### PR TITLE
Some changes from Phts

### PR DESCRIPTION
**Pull request by Kamui-Solo**
Some changes intended to solve problems with tab close buttons.

### CODE REVIEW

**Comment by phts** [comment]
Related original commits (with correct messages):
- phts/tabutils@e5743858c14067a010349c0e016fdfaf4248e40f
- phts/tabutils@3edfa8a8c176ab8e8a4015f5c7eb15f39632825b
- phts/tabutils@a78433551b20aa399519531835a4618f835b37a2
- phts/tabutils@591defee522969ed98c3b169f72e26119f119766

**Comment by yfdyh000** [comment]
Very grateful for this commit and inform!

I will have some fixes before the release of this version. Don't urgent :)

**Comment by yfdyh000** [comment]
@phts Can you review the 9c7b5b9d3f9c0eec2e085c259e1be9d9f94743b7 and comment, thanks.

As well, do you still continues to maintain your fork? I have a bunch [DOTO](https://github.com/yfdyh000/tabutils/wiki/TODO), but there is not enough technical and energy by me...

**Comment by phts** [comment]
@yfdyh000 well I stopped maintaining my fork since your fork had more fixes and improvements. OK I will complete some TODOs if I have a chance.

**Pull request merged**
